### ISSUE TITLE
redis get epic

### ISSUE THREAD

**Issue by joao-fontenele** [joao-fontenele/simple-cache#2]
as a user, I want to make a simple redis get by key with:

  - [ ] have an option to compress producer results? or is it producer responsibility? if it's the producer responsibility, who is responsible for decompressing on read?
  - [ ] e2e tests
  - [ ] have an option to avoid thundering producer calls, or is it producer responsibility?
  - [ ] have an option to set prefixes to the key? (maybe just expect the user to pass the key correctly)
  - [ ] have an option to call producer directly in case of redis faults, circuit break redis?
  - [x] ci
  - [x] docs
  - [x] have an option to rta the performance of producers and cache
  - [x] have an option to refresh keys automatically once a ttl threshold is crossed
  - [x] an optional producer
  - [x] set an optional ttl to the key
  - [x] have an option of in case of cache miss, make the producer call and cache set in background
  - [x] have an option to await the producer and cache set before
  - [x] have an option to override the cache and renew the key with producer data
  - [x] have an option to throw a timeout on the whole get, but request producer and set key in background
  - [x] have an option to circuit break the producer in case of errors? or is it producer responsibility
